#!/usr/bin/env bash

# This bash completions script was generated by
# completely (https://github.com/dannyben/completely)
# Modifying it manually is not recommended
_dotm_completions() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local comp_line="${COMP_WORDS[@]:1}"

  case "$comp_line" in
    'add'*) COMPREPLY=($(compgen -W "--copy --encrypted --force --help --package -c -e -f -h -p" -- "$cur")) ;;
    ''*) COMPREPLY=($(compgen -W "--help --version -h -v add" -- "$cur")) ;;
  esac
}

complete -F _dotm_completions dotm
